export type NationalityInfo = { name: string; flag: string };

export const NATIONALITY_MAP: Record<string, NationalityInfo> = {
    "ABW": { name: "Aruban", flag: "🇦🇼" },
    "AFG": { name: "Afghan", flag: "🇦🇫" },
    "AGO": { name: "Angolan", flag: "🇦🇴" },
    "AIA": { name: "Anguillian", flag: "🇦🇮" },
    "ALA": { name: "Ålandish", flag: "🇦🇽" },
    "ALB": { name: "Albanian", flag: "🇦🇱" },
    "AND": { name: "Andorran", flag: "🇦🇩" },
    "ARE": { name: "Emirati", flag: "🇦🇪" },
    "ARG": { name: "Argentine", flag: "🇦🇷" },
    "ARM": { name: "Armenian", flag: "🇦🇲" },
    "ASM": { name: "American Samoan", flag: "🇦🇸" },
    "ATA": { name: "Antarctican", flag: "🇦🇶" },
    "ATF": { name: "French", flag: "🇹🇫" },
    "ATG": { name: "Antiguan, Barbudan", flag: "🇦🇬" },
    "AUS": { name: "Australian", flag: "🇦🇺" },
    "AUT": { name: "Austrian", flag: "🇦🇹" },
    "AZE": { name: "Azerbaijani", flag: "🇦🇿" },
    "BDI": { name: "Burundian", flag: "🇧🇮" },
    "BEL": { name: "Belgian", flag: "🇧🇪" },
    "BEN": { name: "Beninese", flag: "🇧🇯" },
    "BES": { name: "Dutch", flag: "🇧🇶" },
    "BFA": { name: "Burkinabe", flag: "🇧🇫" },
    "BGD": { name: "Bangladeshi", flag: "🇧🇩" },
    "BGR": { name: "Bulgarian", flag: "🇧🇬" },
    "BHR": { name: "Bahraini", flag: "🇧🇭" },
    "BHS": { name: "Bahamian", flag: "🇧🇸" },
    "BIH": { name: "Bosnian, Herzegovinian", flag: "🇧🇦" },
    "BLM": { name: "Saint Barthélemy Islander", flag: "🇧🇱" },
    "BLR": { name: "Belarusian", flag: "🇧🇾" },
    "BLZ": { name: "Belizean", flag: "🇧🇿" },
    "BMU": { name: "Bermudian", flag: "🇧🇲" },
    "BOL": { name: "Bolivian", flag: "🇧🇴" },
    "BRA": { name: "Brazilian", flag: "🇧🇷" },
    "BRB": { name: "Barbadian", flag: "🇧🇧" },
    "BRN": { name: "Bruneian", flag: "🇧🇳" },
    "BTN": { name: "Bhutanese", flag: "🇧🇹" },
    "BVT": { name: "", flag: "🇧🇻" },
    "BWA": { name: "Motswana", flag: "🇧🇼" },
    "CAF": { name: "Central African", flag: "🇨🇫" },
    "CAN": { name: "Canadian", flag: "🇨🇦" },
    "CCK": { name: "Cocos Islander", flag: "🇨🇨" },
    "CHE": { name: "Swiss", flag: "🇨🇭" },
    "CHL": { name: "Chilean", flag: "🇨🇱" },
    "CHN": { name: "Chinese", flag: "🇨🇳" },
    "CIV": { name: "Ivorian", flag: "🇨🇮" },
    "CMR": { name: "Cameroonian", flag: "🇨🇲" },
    "COD": { name: "Congolese", flag: "🇨🇩" },
    "COG": { name: "Congolese", flag: "🇨🇬" },
    "COK": { name: "Cook Islander", flag: "🇨🇰" },
    "COL": { name: "Colombian", flag: "🇨🇴" },
    "COM": { name: "Comoran", flag: "🇰🇲" },
    "CPV": { name: "Cape Verdian", flag: "🇨🇻" },
    "CRI": { name: "Costa Rican", flag: "🇨🇷" },
    "CUB": { name: "Cuban", flag: "🇨🇺" },
    "CUW": { name: "Curaçaoan", flag: "🇨🇼" },
    "CXR": { name: "Christmas Islander", flag: "🇨🇽" },
    "CYM": { name: "Caymanian", flag: "🇰🇾" },
    "CYP": { name: "Cypriot", flag: "🇨🇾" },
    "CZE": { name: "Czech", flag: "🇨🇿" },
    "DEU": { name: "German", flag: "🇩🇪" },
    "DJI": { name: "Djibouti", flag: "🇩🇯" },
    "DMA": { name: "Dominican", flag: "🇩🇲" },
    "DNK": { name: "Danish", flag: "🇩🇰" },
    "DOM": { name: "Dominican", flag: "🇩🇴" },
    "DZA": { name: "Algerian", flag: "🇩🇿" },
    "ECU": { name: "Ecuadorean", flag: "🇪🇨" },
    "EGY": { name: "Egyptian", flag: "🇪🇬" },
    "ERI": { name: "Eritrean", flag: "🇪🇷" },
    "ESH": { name: "Sahrawi", flag: "🇪🇭" },
    "ESP": { name: "Spanish", flag: "🇪🇸" },
    "EST": { name: "Estonian", flag: "🇪🇪" },
    "ETH": { name: "Ethiopian", flag: "🇪🇹" },
    "FIN": { name: "Finnish", flag: "🇫🇮" },
    "FJI": { name: "Fijian", flag: "🇫🇯" },
    "FLK": { name: "Falkland Islander", flag: "🇫🇰" },
    "FRA": { name: "French", flag: "🇫🇷" },
    "FRO": { name: "Faroese", flag: "🇫🇴" },
    "FSM": { name: "Micronesian", flag: "🇫🇲" },
    "GAB": { name: "Gabonese", flag: "🇬🇦" },
    "GBR": { name: "British", flag: "🇬🇧" },
    "GEO": { name: "Georgian", flag: "🇬🇪" },
    "GGY": { name: "Channel Islander", flag: "🇬🇬" },
    "GHA": { name: "Ghanaian", flag: "🇬🇭" },
    "GIB": { name: "Gibraltar", flag: "🇬🇮" },
    "GIN": { name: "Guinean", flag: "🇬🇳" },
    "GLP": { name: "Guadeloupian", flag: "🇬🇵" },
    "GMB": { name: "Gambian", flag: "🇬🇲" },
    "GNB": { name: "Guinea-Bissauan", flag: "🇬🇼" },
    "GNQ": { name: "Equatorial Guinean", flag: "🇬🇶" },
    "GRC": { name: "Greek", flag: "🇬🇷" },
    "GRD": { name: "Grenadian", flag: "🇬🇩" },
    "GRL": { name: "Greenlandic", flag: "🇬🇱" },
    "GTM": { name: "Guatemalan", flag: "🇬🇹" },
    "GUF": { name: "Guianan", flag: "🇬🇫" },
    "GUM": { name: "Guamanian", flag: "🇬🇺" },
    "GUY": { name: "Guyanese", flag: "🇬🇾" },
    "HKG": { name: "Hong Konger", flag: "🇭🇰" },
    "HMD": { name: "Heard and McDonald Islander", flag: "🇭🇲" },
    "HND": { name: "Honduran", flag: "🇭🇳" },
    "HRV": { name: "Croatian", flag: "🇭🇷" },
    "HTI": { name: "Haitian", flag: "🇭🇹" },
    "HUN": { name: "Hungarian", flag: "🇭🇺" },
    "IDN": { name: "Indonesian", flag: "🇮🇩" },
    "IMN": { name: "Manx", flag: "🇮🇲" },
    "IND": { name: "Indian", flag: "🇮🇳" },
    "IOT": { name: "Indian", flag: "🇮🇴" },
    "IRL": { name: "Irish", flag: "🇮🇪" },
    "IRN": { name: "Iranian", flag: "🇮🇷" },
    "IRQ": { name: "Iraqi", flag: "🇮🇶" },
    "ISL": { name: "Icelander", flag: "🇮🇸" },
    "ISR": { name: "Israeli", flag: "🇮🇱" },
    "ITA": { name: "Italian", flag: "🇮🇹" },
    "JAM": { name: "Jamaican", flag: "🇯🇲" },
    "JEY": { name: "Channel Islander", flag: "🇯🇪" },
    "JOR": { name: "Jordanian", flag: "🇯🇴" },
    "JPN": { name: "Japanese", flag: "🇯🇵" },
    "KAZ": { name: "Kazakhstani", flag: "🇰🇿" },
    "KEN": { name: "Kenyan", flag: "🇰🇪" },
    "KGZ": { name: "Kirghiz", flag: "🇰🇬" },
    "KHM": { name: "Cambodian", flag: "🇰🇭" },
    "KIR": { name: "I-Kiribati", flag: "🇰🇮" },
    "KNA": { name: "Kittitian or Nevisian", flag: "🇰🇳" },
    "KOR": { name: "South Korean", flag: "🇰🇷" },
    "KWT": { name: "Kuwaiti", flag: "🇰🇼" },
    "LAO": { name: "Laotian", flag: "🇱🇦" },
    "LBN": { name: "Lebanese", flag: "🇱🇧" },
    "LBR": { name: "Liberian", flag: "🇱🇷" },
    "LBY": { name: "Libyan", flag: "🇱🇾" },
    "LCA": { name: "Saint Lucian", flag: "🇱🇨" },
    "LIE": { name: "Liechtensteiner", flag: "🇱🇮" },
    "LKA": { name: "Sri Lankan", flag: "🇱🇰" },
    "LSO": { name: "Mosotho", flag: "🇱🇸" },
    "LTU": { name: "Lithuanian", flag: "🇱🇹" },
    "LUX": { name: "Luxembourger", flag: "🇱🇺" },
    "LVA": { name: "Latvian", flag: "🇱🇻" },
    "MAC": { name: "Macanese", flag: "🇲🇴" },
    "MAF": { name: "Saint Martin Islander", flag: "🇲🇫" },
    "MAR": { name: "Moroccan", flag: "🇲🇦" },
    "MCO": { name: "Monegasque", flag: "🇲🇨" },
    "MDA": { name: "Moldovan", flag: "🇲🇩" },
    "MDG": { name: "Malagasy", flag: "🇲🇬" },
    "MDV": { name: "Maldivan", flag: "🇲🇻" },
    "MEX": { name: "Mexican", flag: "🇲🇽" },
    "MHL": { name: "Marshallese", flag: "🇲🇭" },
    "MKD": { name: "Macedonian", flag: "🇲🇰" },
    "MLI": { name: "Malian", flag: "🇲🇱" },
    "MLT": { name: "Maltese", flag: "🇲🇹" },
    "MMR": { name: "Burmese", flag: "🇲🇲" },
    "MNE": { name: "Montenegrin", flag: "🇲🇪" },
    "MNG": { name: "Mongolian", flag: "🇲🇳" },
    "MNP": { name: "American", flag: "🇲🇵" },
    "MOZ": { name: "Mozambican", flag: "🇲🇿" },
    "MRT": { name: "Mauritanian", flag: "🇲🇷" },
    "MSR": { name: "Montserratian", flag: "🇲🇸" },
    "MTQ": { name: "Martinican", flag: "🇲🇶" },
    "MUS": { name: "Mauritian", flag: "🇲🇺" },
    "MWI": { name: "Malawian", flag: "🇲🇼" },
    "MYS": { name: "Malaysian", flag: "🇲🇾" },
    "MYT": { name: "Mahoran", flag: "🇾🇹" },
    "NAM": { name: "Namibian", flag: "🇳🇦" },
    "NCL": { name: "New Caledonian", flag: "🇳🇨" },
    "NER": { name: "Nigerien", flag: "🇳🇪" },
    "NFK": { name: "Norfolk Islander", flag: "🇳🇫" },
    "NGA": { name: "Nigerian", flag: "🇳🇬" },
    "NIC": { name: "Nicaraguan", flag: "🇳🇮" },
    "NIU": { name: "Niuean", flag: "🇳🇺" },
    "NLD": { name: "Dutch", flag: "🇳🇱" },
    "NOR": { name: "Norwegian", flag: "🇳🇴" },
    "NPL": { name: "Nepalese", flag: "🇳🇵" },
    "NRU": { name: "Nauruan", flag: "🇳🇷" },
    "NZL": { name: "New Zealander", flag: "🇳🇿" },
    "OMN": { name: "Omani", flag: "🇴🇲" },
    "PAK": { name: "Pakistani", flag: "🇵🇰" },
    "PAN": { name: "Panamanian", flag: "🇵🇦" },
    "PCN": { name: "Pitcairn Islander", flag: "🇵🇳" },
    "PER": { name: "Peruvian", flag: "🇵🇪" },
    "PHL": { name: "Filipino", flag: "🇵🇭" },
    "PLW": { name: "Palauan", flag: "🇵🇼" },
    "PNG": { name: "Papua New Guinean", flag: "🇵🇬" },
    "POL": { name: "Polish", flag: "🇵🇱" },
    "PRI": { name: "Puerto Rican", flag: "🇵🇷" },
    "PRK": { name: "North Korean", flag: "🇰🇵" },
    "PRT": { name: "Portuguese", flag: "🇵🇹" },
    "PRY": { name: "Paraguayan", flag: "🇵🇾" },
    "PSE": { name: "Palestinian", flag: "🇵🇸" },
    "PYF": { name: "French Polynesian", flag: "🇵🇫" },
    "QAT": { name: "Qatari", flag: "🇶🇦" },
    "REU": { name: "Réunionese", flag: "🇷🇪" },
    "ROU": { name: "Romanian", flag: "🇷🇴" },
    "RUS": { name: "Russian", flag: "🇷🇺" },
    "RWA": { name: "Rwandan", flag: "🇷🇼" },
    "SAU": { name: "Saudi Arabian", flag: "🇸🇦" },
    "SDN": { name: "Sudanese", flag: "🇸🇩" },
    "SEN": { name: "Senegalese", flag: "🇸🇳" },
    "SGP": { name: "Singaporean", flag: "🇸🇬" },
    "SGS": { name: "South Georgian South Sandwich Islander", flag: "🇬🇸" },
    "SHN": { name: "Saint Helenian", flag: "🇸🇭" },
    "SJM": { name: "Norwegian", flag: "🇸🇯" },
    "SLB": { name: "Solomon Islander", flag: "🇸🇧" },
    "SLE": { name: "Sierra Leonean", flag: "🇸🇱" },
    "SLV": { name: "Salvadoran", flag: "🇸🇻" },
    "SMR": { name: "Sammarinese", flag: "🇸🇲" },
    "SOM": { name: "Somali", flag: "🇸🇴" },
    "SPM": { name: "Saint-Pierrais, Miquelonnais", flag: "🇵🇲" },
    "SRB": { name: "Serbian", flag: "🇷🇸" },
    "SSD": { name: "South Sudanese", flag: "🇸🇸" },
    "STP": { name: "Sao Tomean", flag: "🇸🇹" },
    "SUR": { name: "Surinamer", flag: "🇸🇷" },
    "SVK": { name: "Slovak", flag: "🇸🇰" },
    "SVN": { name: "Slovene", flag: "🇸🇮" },
    "SWE": { name: "Swedish", flag: "🇸🇪" },
    "SWZ": { name: "Swazi", flag: "🇸🇿" },
    "SXM": { name: "St. Maartener", flag: "🇸🇽" },
    "SYC": { name: "Seychellois", flag: "🇸🇨" },
    "SYR": { name: "Syrian", flag: "🇸🇾" },
    "TCA": { name: "Turks and Caicos Islander", flag: "🇹🇨" },
    "TCD": { name: "Chadian", flag: "🇹🇩" },
    "TGO": { name: "Togolese", flag: "🇹🇬" },
    "THA": { name: "Thai", flag: "🇹🇭" },
    "TJK": { name: "Tadzhik", flag: "🇹🇯" },
    "TKL": { name: "Tokelauan", flag: "🇹🇰" },
    "TKM": { name: "Turkmen", flag: "🇹🇲" },
    "TLS": { name: "East Timorese", flag: "🇹🇱" },
    "TON": { name: "Tongan", flag: "🇹🇴" },
    "TTO": { name: "Trinidadian", flag: "🇹🇹" },
    "TUN": { name: "Tunisian", flag: "🇹🇳" },
    "TUR": { name: "Turkish", flag: "🇹🇷" },
    "TUV": { name: "Tuvaluan", flag: "🇹🇻" },
    "TWN": { name: "Taiwanese", flag: "🇹🇼" },
    "TZA": { name: "Tanzanian", flag: "🇹🇿" },
    "UGA": { name: "Ugandan", flag: "🇺🇬" },
    "UKR": { name: "Ukrainian", flag: "🇺🇦" },
    "UMI": { name: "American Islander", flag: "🇺🇲" },
    "UNK": { name: "Kosovar", flag: "🇽🇰" },
    "URY": { name: "Uruguayan", flag: "🇺🇾" },
    "USA": { name: "American", flag: "🇺🇸" },
    "UZB": { name: "Uzbekistani", flag: "🇺🇿" },
    "VAT": { name: "Vatican", flag: "🇻🇦" },
    "VCT": { name: "Saint Vincentian", flag: "🇻🇨" },
    "VEN": { name: "Venezuelan", flag: "🇻🇪" },
    "VGB": { name: "Virgin Islander", flag: "🇻🇬" },
    "VIR": { name: "Virgin Islander", flag: "🇻🇮" },
    "VNM": { name: "Vietnamese", flag: "🇻🇳" },
    "VUT": { name: "Ni-Vanuatu", flag: "🇻🇺" },
    "WLF": { name: "Wallis and Futuna Islander", flag: "🇼🇫" },
    "WSM": { name: "Samoan", flag: "🇼🇸" },
    "YEM": { name: "Yemeni", flag: "🇾🇪" },
    "ZAF": { name: "South African", flag: "🇿🇦" },
    "ZMB": { name: "Zambian", flag: "🇿🇲" },
    "ZWE": { name: "Zimbabwean", flag: "🇿🇼" },
};

/**
 * Returns the full nationality name if a 3-letter ISO code is passed,
 * otherwise returns the original input. 
 * Case-insensitive.
 */
export function formatNationalityCode(input: string): string {
    if (!input) return "";
    const cleanInput = input.trim().toUpperCase();
    if (NATIONALITY_MAP[cleanInput]) {
        return NATIONALITY_MAP[cleanInput].name;
    }
    return input;
}

/**
 * Returns the flag emoji for a given nationality name or 3-letter code.
 */
export function getNationalityFlag(input: string): string {
    if (!input) return "";
    const cleanInput = input.trim();
    const upperInput = cleanInput.toUpperCase();
    
    // If it's a 3-letter code
    if (NATIONALITY_MAP[upperInput]) {
        return NATIONALITY_MAP[upperInput].flag;
    }
    
    // Reverse lookup by name
    const match = Object.values(NATIONALITY_MAP).find(
        (info) => info.name.toLowerCase() === cleanInput.toLowerCase()
    );
    
    return match ? match.flag : "";
}
